name: "test and"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Other job
        run: 'true'

      - name: Merge master into staging-next
        id: staging_next
        run: 'true'

      - name: Merge staging-next into staging
        id: staging
        run: 'true'

      - name: Comment on failure
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ failure() }}
        with:
          issue-number: 2
          body: |
            An automatic merge${{ (steps.staging_next.outcome == 'failure' && ' from master to staging-next') || ((steps.staging.outcome == 'failure' && ' from staging-next to staging') || '') }} [failed](https://github.com/NixOS/nixpkgs/actions/runs/${{ github.run_id }}).
