name: CI

on:
  push:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --no-suggest --prefer-dist"

jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'Check rector#7231'
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run rector
        run: |
          nix shell -f 'channel:nixos-unstable' php php.packages.composer -c sh -c 'cd rector-7231 && composer install && vendor/bin/rector'
